# Generated by Django 3.2.6 on 2021-08-16 10:16

import apps.songs_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('index', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.IntegerField()),
                ('loudness', models.FloatField()),
                ('mode', apps.songs_api.models.CustomBooleanField()),
                ('acousticness', models.DecimalField(decimal_places=10, max_digits=50)),
                ('instrumentalness', models.DecimalField(decimal_places=10, max_digits=50)),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('duration_ms', models.IntegerField()),
                ('time_signature', models.IntegerField()),
                ('num_bars', models.IntegerField()),
                ('num_sections', models.IntegerField()),
                ('num_segments', models.IntegerField()),
                ('db_class', models.IntegerField(db_column='class')),
                ('star_rating', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
